# Generated by Django 5.0.1 on 2024-01-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
