# Generated by Django 5.0.1 on 2024-01-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_like_by_post_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
