name: motion_backend
dependencies:
  - pip=23.3.1
  - python=3.12.0
  - psycopg2=2.9.3
  - pip:
    - django==5.0.1
    - djangorestframework==3.14.0
    - djangorestframework_simplejwt==5.3.1
    - pillow==10.2.0
    - drf-yasg==1.21.7
    - flake8
